uNextVec(range) = ((2 - 2 * lambdaSq - 6 * muSq - 4 * sig1 * k / h^2) * uVec(range)...
    + (lambdaSq + 4 * muSq + 2 * sig1 * k / h^2) * (uVec(range+1) + uVec(range-1)) ...
    - muSq * (uVec(range+2) + uVec(range-2)) + (-1 + sig0 * k + 4 * sig1 * k / h^2) * uPrevVec(range) ...
    - 2 * sig1 * k / h^2 * (uPrevVec(range+1) + uPrevVec(range-1))) / (1+sig0 * k);

if bc == "s"
    uVirt1 = 2 * uVec(1) - uVec(2);
    uVirtN1 = 2 * uVec(end) - uVec(end-1);
    
    uNextVec(2) = ((2 - 2 * lambdaSq - 6 * muSq - 4 * sig1 * k / h^2) * uVec(2)...
        + (lambdaSq + 4 * muSq + 2 * sig1 * k / h^2) * (uVec(3) + uVec(1)) ...
        - muSq * (uVec(4) + uVirt1) + (-1 + sig0 * k + 4 * sig1 * k / h^2) * uPrevVec(2) ...
        - 2 * sig1 * k / h^2 * (uPrevVec(3) + uPrevVec(1))) / (1+sig0 * k);
    
    uNextVec(end-1) = ((2 - 2 * lambdaSq - 6 * muSq - 4 * sig1 * k / h^2) * uVec(end-1)...
        + (lambdaSq + 4 * muSq + 2 * sig1 * k / h^2) * (uVec(end-2) + uVec(end)) ...
        - muSq * (uVec(end-3) + uVirtN1) + (-1 + sig0 * k + 4 * sig1 * k / h^2) * uPrevVec(end-1) ...
        - 2 * sig1 * k / h^2 * (uPrevVec(end-2) + uPrevVec(end))) / (1+sig0 * k);
elseif bc == "f"
    %         uVirt2 = uVec(2) - 2 * uVec(1) + 2 * uVirt1;
    %         uVirtN2 = uVec(end-1) - 2 * uVec(end) + 2 * uVirtN1;
    %
    %         uPrevVirt1 = 2 * uPrevVec(1) - uPrevVec(2);
    %         uPrevVirtN1 = 2 * uPrevVec(end) - uPrevVec(end-1);
    
    uNextVec(2) = ((2 - 2 * lambdaSq - 5 * muSq - 4 * sig1 * k / h^2) * uVec(2)...
        + (lambdaSq + 4 * muSq + 2 * sig1 * k / h^2) * (uVec(3)) ...
        + (lambdaSq + 2 * muSq + 2 * sig1 * k / h^2) * (uVec(1)) ...
        - muSq * uVec(4) + (-1 + sig0 * k + 4 * sig1 * k / h^2) * uPrevVec(2) ...
        - 2 * sig1 * k / h^2 * (uPrevVec(3) + uPrevVec(1))) / (1+sig0 * k);
    
    uNextVec(end-1) = ((2 - 2 * lambdaSq - 5 * muSq - 4 * sig1 * k / h^2) * uVec(end-1)...
        + (lambdaSq + 4 * muSq + 2 * sig1 * k / h^2) * (uVec(end-2)) ...
        + (lambdaSq + 2 * muSq + 2 * sig1 * k / h^2) * (uVec(end)) ...
        - muSq * uVec(end-3) + (-1 + sig0 * k + 4 * sig1 * k / h^2) * uPrevVec(end-1) ...
        - 2 * sig1 * k / h^2 * (uPrevVec(end-2) + uPrevVec(end))) / (1+sig0 * k);
    
    
    uNextVec(1) = ((2 - 2 * lambdaSq - 2 * muSq - 4 * sig1 * k / h^2) * uVec(1)...
        + (2 * lambdaSq + 4 * muSq + 4 * sig1 * k / h^2) * uVec(2) ...
        - 2 * muSq * uVec(3) + (-1 + sig0 * k + 4 * sig1 * k / h^2) * uPrevVec(1) ...
        - 4 * sig1 * k / h^2 * uPrevVec(2)) / (1+sig0 * k);
    
    uNextVec(end) = ((2 - 2 * lambdaSq - 2 * muSq - 4 * sig1 * k / h^2) * uVec(end)...
        + (2 * lambdaSq + 4 * muSq + 4 * sig1 * k / h^2) * uVec(end-1) ...
        - 2 * muSq * uVec(end-2) + (-1 + sig0 * k + 4 * sig1 * k / h^2) * uPrevVec(end) ...
        - 4 * sig1 * k / h^2 * uPrevVec(end-1)) / (1+sig0 * k);
    
    %         uNextVec(1) = ((2 - 2 * lambdaSq - 6 * muSq - 4 * sig1 * k / h^2) * uVec(1)...
    %             + (2 * lambdaSq + 4 * muSq + 4 * sig1 * k / h^2) * uVec(2) ...
    %             - 2 * muSq * uVec(3) + (-1 + sig0 * k + 4 * sig1 * k / h^2) * uPrevVec(1) ...
    %             - 4 * sig1 * k / h^2 * uPrevVec(2)) / (1+sig0 * k);
    %         uNextVec(end) = ((2 - 2 * lambdaSq - 6 * muSq - 4 * sig1 * k / h^2) * uVec(end)...
    %             + (2 * lambdaSq + 4 * muSq + 4 * sig1 * k / h^2) * uVec(end-1) ...
    %             - 2 * muSq * uVec(end-2) + (-1 + sig0 * k + 4 * sig1 * k / h^2) * uPrevVec(end) ...
    %             - 4 * sig1 * k / h^2 * uPrevVec(end-1)) / (1+sig0 * k);
end